---
#
# Playbook to install the postgres and pgpool cluster
#

- hosts: prodpsql01
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - /vagrant/install/group_vars/postgres_vars.yml
  roles:
    - { role: postgres-master }

- hosts: prodpsql02
  remote_user: "{{ ansible_system_user }}"
  vars_files:
    - /vagrant/install/group_vars/postgres_vars.yml
  roles:
    - { role: postgres-slave }

#- hosts: pool0*
#  remote_user: "{{ ansible_system_user }}"
#  vars_files:
#    - group_vars/postgres_vars.yml
#  roles:
#    - { role: pgpool }
